
/*
 * TIMER_Config.h
 *
 * Created: 16/09/2023 14:23:06
 *  Author: Mostafa Maher
 */ 

#ifndef	TIMER0_CONFIG_H_
#define TIMER0_CONFIG_H_

/*Timer Prescaler Options:
 * 0- TIMER0_STOPPED
 * 1- TIMER0_NO_PRESCALER
 * 2- TIMER0_8_PRESCALER
 * 3- TIMER0_64_PRESCALER
 * 4- TIMER0_256_PRESCALER
 * 5- TIMER0_1024_PRESCALER
 * 6- TIMER0_EXTERNAL_CLOCK_SOURCE_FALLING_EDGE
 * 7- TIMER0_EXTERNAL_CLOCK_SOURCE_RISING_EDGE
 */
#define TIMER0_SET_PRESCALER   TIMER0_64_PRESCALER

/*TIMER0 Modes Options:
 * 1- TIMER0_NORMAL_MODE
 * 2- TIMER0_CTC_MODE
 * 3- TIMER0_PHASECORRECT_PWM_MODE
 * 4- TIMER0_FAST_PWM_MODE
 */

#define TIMER0_SET_MODE   TIMER0_PHASECORRECT_PWM_MODE

/*Timer0 CTC Interrupt Options:
 * 1- TIMER0_CTC_INTERRUPT_ENABLED
 * 2- TIMER0_CTC_INTERRUPT_DISABLED
 */

#define TIMER0_SET_CTC_INTERRUPT   TIMER0_CTC_INTERRUPT_DISABLED

/*Timer0 CTC OC0 PIN Options:
 * 1- TIMER0_OC0_PIN_DISCONNECTED
 * 2- TIMER0_OC0_PIN_TOGGLE
 * 3- TIMER0_OC0_PIN_SET
 * 4- TIMER0_OC0_PIN_CLR
 */
#define TIMER0_SET_OC0_PIN_MODE  TIMER0_OC0_PIN_TOGGLE

/*Timer0 PWM MODE Options:
 * 1- TIMER0_NON_INVERTING_PWM
 * 2- TIMER0_INVERTING_PWM
 */
#define TIMER0_SET_PWM_MODE  TIMER0_INVERTING_PWM

#endif 